### ISSUE TITLE
user-friendly LuaJIT bindings

### ISSUE THREAD

**Issue by sonoro1234** [tversteeg/luajit-imgui-bindings#1]
Hi,

From `Generate user-friendly LuaJIT bindings for ImGui` I deduce that you find https://github.com/sonoro1234/LuaJIT-ImGui bindings are not user-friendly enough?

How would there be more user-friendly?

**Comment by tversteeg** [comment]
Sorry if that sentence came across as  offending, that wasn't my intention, I didn't mean to imply that your bindings aren't user friendly.

What I'm trying to reach with this repository is to generate regular Lua bindings that wrap the LuaJIT bindings so the LuaJIT C internals aren't exposed.

I want to generate something like this:

```lua
local ffi_v = ffi.new("bool[1]", false)
--- ImGui generated function: `ImGui/Checkbox`.
--- ImGui source location: `imgui:458`.
--- @arg:string ImGui: _const char*_
--- @arg:any The type of this argument can be one of the following: `boolean`, `{boolean, ...}` or `cdata`. ImGui: _bool*_
--- @return:boolean,any ret, v
function gui.checkbox(label, v)
	arg_check(label, "string", 1, true)
	local type_v = type(v)
	if type_v == "table" then
		for i = 1, #v do
			ffi_v[i - 1] = v[i]
		end
	elseif type_v == "cdata" then
		ffi_v = v
	elseif type_v ~= "nil" then
		ffi_v[0] = v
	end
	local ret = lib.igCheckbox(label, v ~= nil and ffi_v or nil)
	if type_v == "table" then
		for i = 1, #v do
			v[i] = ffi_v[i - 1]
		end
	elseif type_v == "cdata" then
		v = ffi_v
	else
		v = ffi_v[0]
	end
	return ret, v
end
```

So that a simple `local changed, result = gui.checkbox("label", state)` can be used for example.

My goal is to abstract away the FFI specific code and ImGui-based code formatting.

**Comment by sonoro1234** [comment]
> Sorry if that sentence came across as offending, that wasn't my intention

That is not offending, I am just curious.

> My goal is to abstract away the FFI specific code and ImGui-based code formatting.

I see. I will follow the development with interest.
